FROM python:3.9
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN mkdir -p /root/ryanair
COPY ryanair/ /root/ryanair
RUN ls -la /root/ryanair/*
ENTRYPOINT [ "pytest", "/root/ryanair/test/TestCase.py" ]